### ISSUE TITLE
Accommodate chain loading, please.

### ISSUE THREAD

**Issue by coder65535** [Hamcha/lumaupdate#11]
I use BootAnim9 to display a boot animation before AuReiNand (Well, Luma3DS now) loads. As a result, my AuReiNand loader is arm9payload.bin. Could you please add support for those of us that chainload AuReiNand? I would love to use this auto-updater, but right now it would overwrite BootAnim9.

**Comment by gabe565** [comment]
Not the Dev, but you should be able to set the payload path in the config (see the latest release) and it will automatically store the AuReiNand payload there and automatically patch it for that path.

**Comment by gabe565** [comment]
Then it shouldn't even affect your BootAnim9 payload. Will just replace the (now) Luma3DS payload

**Comment by coder65535** [comment]
I got linked to an old release rather than the current release, oops.

This is perfect now, thanks.
