### ISSUE TITLE
A9LH version?

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/lumaupdate#14]
Could be useful to have a slim version as a A9LH payload for restoring backups (especially with hourlies) or switch between versions (hourly/stable).

Just an idea, haven't decided yet.

**Comment by Brawl345** [comment]
That'd be great! And btw. thanks for making this app :)

**Comment by astronautlevel2** [comment]
Depends what you want to do with the a9lh version. Restoring backups is possible, but doing something like downloading a different payload won't be possible (unless someone figures out netcode in a9lh ?)

**Comment by Plailect** [comment]
For anything network related you'd have to write your own arm9loaderhax wifi driver since none currently exists to my knowledge. Good luck if you decide to attempt that.

**Comment by Hamcha** [comment]
The A9LH I had in mind was just for restoring backups and the likes, making a full fledged updater for A9LH is way outside my capabilities.

**Comment by quizque** [comment]
Well if the A9LH .bin file got corrupt and it had to be replaced, it would need to be done trough a computer because if it's corrupt it may not load. Also with the file size check and file hashing it should no longer be a problem.

**Comment by Hamcha** [comment]
My case scenario is mostly people who use hourlies and want to go back because of bugs. This thing is a huge maybe anyway.

**Comment by Hamcha** [comment]
Tried and.. it isn't worth it.
