### ISSUE TITLE
Version for Menuhax users

### ISSUE THREAD

**Issue by xxbilxx** [Hamcha/lumaupdate#18]
Could you please modify your project to allow the option to download the new Luma3DS.dat file from the github to update, instead of the arm9loaderhax.bin?

Some users simply do not have the time to install arm9loaderhax (like me), or do not want to take the risk of an additional downgrade. This addition to your program would be great for menuhax/coldboot users!

**Comment by Hamcha** [comment]
Sounds like a nice idea for a future version!

Since I want to release 1.2.0 to stop people from getting dev updates ASAP, I'll think about doing it for 1.3

**Comment by Hamcha** [comment]
Added in a6b7560 and 8eb8830
