### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/lumaupdate#19]
The LumaUpdater Updater joke is old now.

This is probably easy enough with 3dsx if the HBLauncher is kind enough to point us to our name (via argv, I'd assume).

CIA is.. ugh.

**Comment by LinkofHyrule89** [comment]
I guess I didn't understand this is what I wanted :P Well hopefully we see it soon so all our updates can be updated on the 3ds :)

**Comment by quizque** [comment]
You can take a look at [this](https://github.com/llakssz/CIAngel/blob/master/source/cia.c) for installing the CIA.

**Comment by Hamcha** [comment]
Autoupdating for both CIA and 3DSX is in, closing this issue
