### ISSUE TITLE
Hourlys for dev-mode, too?

### ISSUE THREAD

**Issue by d0k3** [Hamcha/lumaupdate#21]
Just gave your tool a first try, looking good! What I'm missing, though, is hourlys for the dev version of Luma3DS. Any chance this will be added later?

BTW; very much out of scope, but I'd like to have something like this for my tools (Decrypt9WIP, EmuNAND9, GodMode9), too, Maybe, if you are interested in this, you can expand the functionality to a full fledged A9LH payload updater later on? :)

**Comment by Hamcha** [comment]
The hourlies are pulled by @astronautlevel2's website [Alex's Luma3DS Builds](https://astronautlevel2.github.io/Luma3DS/), which does not provide dev builds. If he ever starts providing dev builds I'll be glad to add them!

About the more generic uploader. I kinda had an idea for that but it would be a separate project (though probably sharing some of the code), that is if I really want to do it at all. I'm kinda busier than usual as of lately so I wonder if I'll have time to work on this project, let alone another updater.

But you never know I guess?

**Comment by astronautlevel2** [comment]
I'll probably add dev builds to my site once I decide to add dev builds to my own updater (Soon TM)

I have other features I'm going to implement first though, so it may be a week or so before dev builds are up on my site.

**Comment by d0k3** [comment]
Okay, sounds good! If I can do anything from my side to make such a generic updater easier to do, just let me know. I'll have a working nightly page soon, too.

**Comment by Plailect** [comment]
http://astronautlevel2.github.io/Luma3DSDev/

**Comment by Hamcha** [comment]
Nice! I'll have them in 1.3 for sure!

Thanks @astronautlevel2 for going through all the trouble!

**Comment by Hamcha** [comment]
Dev hourlies are in and working, closing!
