### ISSUE TITLE
Showing changelogs?

### ISSUE THREAD

**Issue by d0k3** [Hamcha/lumaupdate#22]
I know, this is not exactly trivial to code, but (optionally) showing changelogs when updating to a new release version would be great.

**Comment by Hamcha** [comment]
Sounds like a delightful idea, probably not that hard to make as well (I'm already parsing json, just needs to strip the markdown from the release text)

I was planning some big changes for 1.3, and this sounds like a perfect candidate.

**Comment by Hamcha** [comment]
Added some crude support to release notes with f389af2

**Note to self (or contributors):**
The word wrapping is horrible (should at least be word-based, not char-based) and the `stripMarkdown` function is an empty stub. Consider fixing either (or both) of those before releasing.

**Comment by d0k3** [comment]
See here for an example on how to do word based last line wrapping:
https://github.com/d0k3/CTRXplorer/blob/master/source/ui.cpp
(line 722 and following) 

Also, thanks for implementing this!

**Comment by Hamcha** [comment]
Proper word wrapping (6af72eb) and some markdown filtering (at least the noisy kind) (6e3631d) is done!

Closing this.
