### ISSUE TITLE
Download status

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/lumaupdate#24]
Downloading can take a while, so showing some progress might be handy (and not super hard since we have progress bars now)

**Comment by favna** [comment]
snip

**Comment by solress** [comment]
It can take a while? The longest it ever took for me is 2 seconds,  and I don't even have good internet or anything.

**Comment by astronautlevel2** [comment]
Let's try to avoid harassing devs, please. Just because you don't see a need for a feature doesn't mean there is none.

**Comment by Ordim3n** [comment]
the only situation that it would take long is with 2 000 000 people on your wifi at the same time. Or if you're using dial up. (If you have dial up, it's time to realise that it's 2016)

**Comment by Hamcha** [comment]
To clarify with yesterday's comments:

A regular release (or dev release) is around 240KB and it does take up to like 5 seconds to get it (depending on internet, wifi etc) and I think it's better to write something like a progress than to block and look like the app has hanged (if you ever used CHMM you should know how bad that looks).

I've already implemented some preliminary support for it in 9f0801e but it looks like it's gonna take more work and I was already ready to scrap it. The only reason I wanted to do this was because it looked like it was going to take a couple hours at most without bringing in too much complexity.

Still gonna keep it open, might find an use for it "sometime later".
