### ISSUE TITLE
No longer properly compiles (on Windows?)

### ISSUE THREAD

**Issue by ghost** [Hamcha/lumaupdate#25]
A few others along with myself have been attempting to compile LumaUpdate for most of the day, and have encountered a few errors during compilation: 
1. It isn't compatible with the latest ctrulib. Seems to require version 863ea8ef68fa2b0736c4bd103d7a85b714dd2253, which was before the "great breakage". This was fixed in a [fork](https://github.com/SkaarjK/lumaupdate) by SkarrjK. 
2. The work folder "out" is required; if it isn't present compilation will fail with: 
   `linking lumaupdate.elf
   c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot open output file c:/devkitPro/lumaupdate/out/lumaupdate.elf: No such file or directory
   collect2.exe: error: ld returned 1 exit status
   make: *** [/c/devkitPro/lumaupdate/out/lumaupdate.elf] Error 1` 
   However, this folder is not included in the git nor is it generated by the makefile, requiring it to be manually created. This was also fixed in SkaarjK's [fork](https://github.com/SkaarjK/lumaupdate).
3. ctrulib isn't properly detected when generating lumaupdate.elf, resulting in: 
   `linking lumaupdate.elf
   c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lctru
   collect2.exe: error: ld returned 1 exit status
   make: *** [/c/devkitPro/lumaupdate/out/lumaupdate.elf] Error 1`
   This error occurs with both the main branch (with the old ctrulib) and with SkarrkjK's fork (with the newest ctrulib). DevkitPro/ARM as well as ctrulib were all correctly setup as environmental variables, so I'm not really sure why it suddenly fails to detect ctrulib.

**Comment by ghost** [comment]
I haven't figured out the exact issue yet, but I'm guessing issue 3 is some sort of cross-platform makefile incompatibility; a user in the #cakey IRC channel was able to properly compile SkaarjK's fork (i.e. with issues 1 and 2 fixed) on Debian, but the Windows users that attempted (including myself) all ran into issue 3

**Comment by Hamcha** [comment]
Hi @AileSc  
I have merged SkarrkjK's changes and tested and everything works on my environment (which is running Windows 10).

Are you on IRC? Feel free to bug in private (or in channel, if you mention me) and we can look at that issue together I guess?

Thanks for the very extensive report and for pointing me to SkarrkjK's fork, by the way!

**Comment by ghost** [comment]
Thank you. I am on IRC, under the username Tohka. However, as of a few hours ago, you're actually the second Windows user that was able to get it to compile successfully, meaning there must be something wrong with my and those other user's dev environments. The only thing I can think of that would cause such an error would be incorrectly set environmental variables. Could you type "set" into a command window and share the devkitPro/ARM/3ds-related variables that it shows are set? 

And no problem, happy to help. Thank you again.

**Comment by ghost** [comment]
Given that issue 1 and 2 have been fixed and merged, and issue 3 was found to be due to a missing file, I think it's safe to say this has been resolved. 

Thank you Hamcha, I appreciate the help.
