### ISSUE TITLE
"Dev hourly" option is broken; fetches an invalid URL.

### ISSUE THREAD

**Issue by ghost** [Hamcha/lumaupdate#26]
Just thought I'd let you know that the "dev hourly" function seems to be broken. It attempts to download the payload from an incorrect URL. It seems to use the logic for stable builds, i.e. 
`std::string url = std::string("https://astronautlevel2.github.io/Luma3DS/builds/Luma-") + hourlyName + ".zip";` 
instead of 
`std::string url = std::string("https://astronautlevel2.github.io/Luma3DSDev/builds/Luma-") + hourlyName + ".zip";`

So, for example, it asks for https://astronautlevel2.github.io/Luma3DS/builds/Luma-ca587692.zip instead of https://astronautlevel2.github.io/Luma3DSDev/builds/Luma-ca587692.zip. [Here](https://i.imgur.com/mS15cMQ.png) is a screenshot of the issue.

**Comment by Hamcha** [comment]
Oops! Thanks for the report, I'll fix it ASAP!

**Comment by Hamcha** [comment]
Tested with latest changes (043318e) and working. Closing.
