### ISSUE TITLE
Check for partial downloads / corrupt archives

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/lumaupdate#29]
One time one user said on one reddit thread that something like this happened.

Seems sort of unlikely, but maybe considering adding some checks wouldn't be bad…

**Comment by quizque** [comment]
That's what the .bin.bak file is for but it would be nice. But, for this to happen Luma3DS would need to have checksums(sha,md5 ect) or he would need to host the checksum file him self

**Comment by Hamcha** [comment]
I was actually thinking of a really stupid check (like file size), if that matches and the archive can be opened and extracted, the chance of it being broken (but somehow working) are low enough.

An added check that can be done (as long as the file is small) is the MD5 sum.
Github uses AWS S3 to host files (and both official and hourlies use it) and S3 provides an "Etag" header which can be computed in different ways, but most of the time (unless multipart upload is involved, which only happens with big enough files) the ETag will be the MD5 of the uploaded file.

I think I'd make this second check optional since it 1. Might break in some cases 2. Take time to calculate the MD5 of the archive.

**Comment by quizque** [comment]
It shouldn't take that long to calculate MD5. But also I got a question, Now this is a bit off topic but due to where I am right now I can't visit many pages and must do it trough email, but anyway my question is how did you make a 3d model banner?!?!?!? There is a mass lack of 3d banners in 3ds homebrews because most people don't know how to do it. If you know of a tutoiral I missed during my google serch please link it.

**Comment by Hamcha** [comment]
I haven't used a tutorial (or found one when I searched). but it's sort of simple:

[Every File Explorer](https://gbatemp.net/threads/release-every-file-explorer.373615/) has a OBJ -> CGFX converter. Just create your OBJ with model and texture mapped with your 3D modelling app of choice, then follow this path through EFE:
![EFE -> New from File -> Nintendo 3DS Plugin -> CTR Graphics](http://puu.sh/plrXD/aae77c156f.png)

You need to get scale and rotation right in your OBJ as they're kinda messed up (you can use my luma model as reference).

Since there are some issues on how textures are handled (alpha in particular) and I'd love a command line tool for doing the conversion, I'm working on a CGFX toolchain myself, but it's in a very primitive stage right now.

**Comment by quizque** [comment]
Ok thanks once i get it working I'll put a tutorial on GBATemp or Reddit

**Comment by quizque** [comment]
So after a lot of fails  trying to make a 3d banner I gave up, but I decided to see what would happen if I did it with your model. So after opening it in Wings 3D > Adding Textures > Exporting > Converting in EFE this happened. 
![capture](https://cloud.githubusercontent.com/assets/13785390/15945364/166a5766-2e60-11e6-833b-9984cdc778ab.PNG)
Its the same thing that has been happening to the other models and I can find a solution :/
I use EFE to convert and Wings 3D to make the models.

**Comment by Hamcha** [comment]
Sorry but I have no idea how that might have happened. I've only had issues with semitransparent textures so far, never something like that.

Have you been using `luma.wings` or `luma.merged.wings` ? The latter one has proper rotation/scale and has been all merged all in one mesh (and it's what I used to create the CGFX)

**Comment by quizque** [comment]
I have used the non merged one I'll try it rn

**Comment by Hamcha** [comment]
To get back on topic, Integrity checks are in (both of them) with 245a597

Testing required.

**Comment by quizque** [comment]
I can test right now, I'll get back with the results

**Comment by quizque** [comment]
When I tried to build the new version it fails, [this is the log.](http://pastebin.com/SNYGYY4j) I got makerom and bannertool in my PATH the new ctrulib version and zlib.

**Comment by Hamcha** [comment]
What ctrulib commit are you compiling it with? I've just updated to [3a10698](https://github.com/smealum/ctrulib/commit/3a10698964db5046ec55234daef9d7512a02ace0) and it compiles fine.

**Comment by quizque** [comment]
The latest one

**Comment by Hamcha** [comment]
"The latest one" works for me, though. Do you really have it installed correctly and everything? The error you reported happens with the stable version (1.1.0).

Also, if you want to continue please query me on IRC (Freenode, Efnet) or use emails directly to santo@padrepio.in

This issue has been resolved with e450d80.

**Comment by quizque** [comment]
Odd I'll try latter
