### ISSUE TITLE
Add option to select path for BootAnim9 users.

### ISSUE THREAD

**Issue by YozenPL** [Hamcha/lumaupdate#33]
Hello,

Could you please add path selection for BootAnim9 users (for checking version and download.)?
BootAnim9 - default path for payload is SD:/anim/arm9payload.bin

**Comment by Hamcha** [comment]
I don't understand the request, are you asking for custom luma a9lh paths? Those have been in since forever. Just set the "payload path" in the [configuration file](https://github.com/Hamcha/lumaupdate/blob/master/lumaupdater.cfg#L1) (no sd:/ prefix). Otherwise please be more specific.

**Comment by YozenPL** [comment]
I'm dumb. I forgot about config file.
