### ISSUE TITLE
O3DS not working in 5.5

### ISSUE THREAD

**Issue by timbiotic** [Hamcha/lumaupdate#36]
Multiple reports of the old 3ds not working in 5.5.  Tested and working fine in 5.2.  I haven't tried other releases.

**Comment by Hamcha** [comment]
I'll need some more information than that.
What version of Luma Updater is giving issues?
Also, what do you mean by "not working"? Does it give an error, does it crash when starting it?

I use a O3DS for testing and debugging (and a N3DS for pre-release tests), so it's definitely not an issue with all O3DSs. I don't even have N3DS-only code.

**Comment by timbiotic** [comment]
i think I posted on the wrong area. I thought this was the luma GitHub.  Sorry, basically I have determined that with my o3ds I have to clean it up pre the faq on the website for luma3ds.  But the links they post have viruses so I cant get the firmware files I need to fix it.  you can kill this issue as it should be on the other GitHub for luma3ds
