### ISSUE TITLE
[BUG] Current Version

### ISSUE THREAD

**Issue by Ninjistix** [Hamcha/lumaupdate#44]
did an update for Luma3DS using this, and it no longer shows my Current Version, went from 5.5>6.0  (no longer saw current version) > 6.0.1 (Still no current version)

**Comment by Hamcha** [comment]
That's weird, I do see it in mine, I'll see if I can reproduce it on my other 3DS

**EDIT**: Ok it definitely broke with 6.0.1

**Comment by suzsuzuki** [comment]
It happens with me too

**Comment by nightwind84** [comment]
mee too, same problem no current version after update :(

**Comment by RhanCandia** [comment]
+1

**Comment by CoolFangs** [comment]
Been having this issue since some of the later 5.5 hourlies.

**Comment by RinMaru** [comment]
yep it don't show what version of luma is installed anymore

**Comment by akirayuki** [comment]
Same problem here

**Comment by RhanCandia** [comment]
I've updated to the latest Luma version. Still doesn't show the current version on Luma Updater.

**Comment by Hamcha** [comment]
The issue has been fixed in ea739dc (thanks to @astronautlevel2 for doing the detective work for me).

I'm releasing a new version that fixes the issue right now.

**Comment by Ninjistix** [comment]
yup everything's working again.. thanks @Hamcha
