### ISSUE TITLE
[Suggestion] Possibility to update payloads

### ISSUE THREAD

**Issue by suzsuzuki** [Hamcha/lumaupdate#45]
This is not an issue, but a suggestion. I think will be fine if there's a way to update the default payloads (Decrypt9, Hourglass9 and EmuNAND9) used in Plailect guide. Do you think it's possible?

**Comment by Hamcha** [comment]
I get this suggestion quite often when talking about Luma and I keep rejecting it: It would add an incredible cost in complexity and I don't feel like it's worth it for this tool specifically.

**Comment by suzsuzuki** [comment]
No problem, Multiupdater does the job.  https://github.com/LiquidFenrir/MultiUpdater
