### ISSUE TITLE
Luma 6.0.1 showing VER instead of Sys

### ISSUE THREAD

**Issue by Barcia997** [Hamcha/lumaupdate#46]
Should I worry? Is this normal?

**Comment by suzsuzuki** [comment]
That's because you updated.  
Hold select on boot to enter the Luma3DS menu.

Use the A button and the D-Pad to turn on the following:

"Show current NAND in System Settings"

It solves your problem.

**Comment by Ninjistix** [comment]
@Barcia997 i didnt notice that, and @suzsuzuki that helped fix my issue too :dango:

**Comment by RhanCandia** [comment]
This should be marked resolved.

**Comment by Hamcha** [comment]
This was an issue with Luma3DS, not the updater (and it's been resolved), closing
