### ISSUE TITLE
Trying to install A9LH payload when type is homebrew

### ISSUE THREAD

**Issue by ghost** [Hamcha/lumaupdate#47]
Okay so I installed cia version of Lumaupdate & I tried to update ( I had Luma 6.0  ) and it errors out with "FATAL: could not find 3DS/Luma3DS/Luma3DS.3dsxFATEL Could not get A9LH" in my config file I set it to homebrew because it stays red when I try to load luma3ds.dat with CTRBootManager I've tried updating with Luma3DS loaded & also ReiNand loaded both failed. Any help would be nice

**Comment by ghost** [comment]
Well I fixed it I changed it to Menuhax btw what is homebrew used for?

**Comment by Hamcha** [comment]
Hi, sorry I could not be of help but I've been quite busy lately (most of
my coworkers are on vacation so I have to make up for them). Homebrew
should only update Luma3DS.3dsx (which is specified by its Payload path) if
you use Luma3DS via Homebrew launcher.
If you use CTRBootManager you need the "menuhax" update option as the luma
payload you load is Luma3ds.dat and not Luma3ds.3dsx file.

Il giorno gio 25 ago 2016 alle ore 09:55 LMN101 notifications@github.com
ha scritto:

**Comment by ghost** [comment]
I don't load it by the .dat file I load it by .3dsx because .dat files have lower chances than .3dsx

**Comment by Hamcha** [comment]
In that case can you show me what config did you use when you were using
the homebrew option? There might have been an issue with it.

Il giorno gio 25 ago 2016 alle ore 10:09 LMN101 notifications@github.com
ha scritto:

**Comment by ghost** [comment]
In the config:
payload type = homebrew
payload path = /3ds/Luma3DS/Luma3DS.3dsx
Log Enable = no
backup = no

**Comment by Hamcha** [comment]
And the error is still `FATAL: could not find 3DS/Luma3DS/Luma3DS.3dsx`?

When does the error happen? Can you change "log enable" to "yes" (`log enable = yes`) and post the generated log file (`lumaupdater.log`) somewhere (like [here](https://gist.github.com)) while trying to use the homebrew option? That would be quite helpful.

**Comment by ghost** [comment]
so want me to change log enable to yes for homebrew?

**Comment by Hamcha** [comment]
yes, and then post the content of `lumaupdater.log` after it gives you the error

**Comment by ghost** [comment]
Got the log:
Checking for new Luma3DS Updater releases...
Downloading https://api.github.com/repos/Hamcha/lumaupdate/releases/latest...
Download progress: 4424 / 4424
Downloaded 4424 bytes
JSON parsed successfully!
Release found: v1.4.1
Changelog found.
Current updater is already at latest release.
Trying detection of current payload version...
Loaded existing payload in memory, searching for version number...
Weird version string: it's empty (?)
Downloading https://api.github.com/repos/AuroraWright/Luma3DS/releases/latest...
Download progress: 4835 / 4835
Downloaded 4835 bytes
JSON parsed successfully!
Release found: 6.0.1
Found version: Luma3DSv6.0.1-dev.7z
Found version: Luma3DSv6.0.1.7z
Release description found.
Downloading https://raw.githubusercontent.com/astronautlevel2/Luma3DS/gh-pages/lastCommit...
Download progress: 9 / 9
Downloaded 9 bytes
Downloading https://raw.githubusercontent.com/astronautlevel2/Luma3DSDev/gh-pages/lastCommit...
Download progress: 9 / 9
Downloaded 9 bytes
Payload backup is disabled in config, skipping...
Downloading https://github.com/AuroraWright/Luma3DS/releases/download/v6.0.1/Luma3DSv6.0.1.7z
Download progress: 141582 / 141582
Download complete! Size: 141582
Integrity check #1 [OK]
Integrity check #2 [OK]

Extracting payload [ERR]
FATAL: Could not find 3DS/Luma3DS/Luma3DS.3dsxFATAL
Could not get A9LH payload...

**Comment by Hamcha** [comment]
Congratulation, you found a bug!

The file is in the archive but LumaUpdater has trouble finding it apparently, I'll have to look at it. (As soon as I fix my broken dev environment)

**Comment by ghost** [comment]
okay so what now?

**Comment by ghost** [comment]
I need my 3ds with this stuff for tomorrow

**Comment by Hamcha** [comment]
Try using hourlies instead of the stable release, maybe the ZIP searcher works. The 7z is apparently broken and there isn't anything I can do before tomorrow, sorry.

**Comment by ghost** [comment]
same error could not get A9LH payload

**Comment by Hamcha** [comment]
..That's weird indeed. Sorry but I cannot do anything for you in the timeframe you described, you'll have to put the 3dsx file by hand (via SD or FTP)

**Comment by ghost** [comment]
one last thing with the menuhax option if you have it directed to a 3dsx file what does it download?

**Comment by Hamcha** [comment]
It downloads the `Luma3ds.dat` file, so if you specify a 3dsx path it will just rename it to a 3dsx file (which won't work I assume)

**Comment by ghost** [comment]
well damn it

**Comment by ghost** [comment]
I was looking in the Luma3DS 6.0.7 files & I found in the menuhax folder a boot.3dsx haven't tried it yet would that be any use?

**Comment by Hamcha** [comment]
No it won't, just use the `3ds/Luma3DS/Luma3DS.3dsx` file

**Comment by ghost** [comment]
okay

**Comment by LMN101** [comment]
I know I should get A9LH but I'm scared that I will screw it up

**Comment by LMN101** [comment]
any tips for A9LH?

**Comment by ghost** [comment]
I'm reopening this because this is still present on 1.4.2 with the same error

**Comment by ghost** [comment]
BTW here is a screenshot if I can figure out how to put one in
![top_0006](https://cloud.githubusercontent.com/assets/19201672/18046917/87dd762e-6e1d-11e6-89bd-c9fafc2f45b4.png)
![bot_0006](https://cloud.githubusercontent.com/assets/19201672/18046921/8cc8a4ba-6e1d-11e6-830a-8e4ff1a5118b.png)

**Comment by ghost** [comment]
I'm closing this because I now have A9LH so this is not related anymore
