### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by YozenPL** [Hamcha/lumaupdate#49]
I'm using BootAnim9 and I'm not able to update playload using Luma Updater 1.4.2 (same problem with older versions).

LumaUpdater shows the latest version and when I press "Install latest hourly (xxxxxx)" it says that "Update complete". But it is not. I'm still using my previous version.

Content of lumaupdater.cfg:
payload path = anim/arm9payload.bin
log enable = yes
selfupdate = yes
backup = yes

**Comment by CouldBeWolf** [comment]
Same issue. But I'm using ShadowNAND so the path for me is /homebrew/3ds/boot.bin
The backup is made without issue, but nothing else is done.

Edit: And I couldn't find a log anywhere.

**Comment by ghost** [comment]
Try manually installing the hourly version & check the version

**Comment by YozenPL** [comment]
I install f221915a version manually from 71c5404b and I wanted to update it to the newest version (a84f393b).
Same issue. I'm still on f221915a

**Comment by CouldBeWolf** [comment]
Version check works fine. And backup works, but it doesn't seem to do anything else when it's given an alternative path.

**Comment by ghost** [comment]
I'm stuck with 3dsx version of luma
