### ISSUE TITLE
NAND Payload Updating Support

### ISSUE THREAD

**Issue by cheatfreak47** [Hamcha/lumaupdate#55]
As the recent hourly updates Luma3DS and latest A9LH stable, it is now possible to boot Luma3DS from  the SysNAND's CTR NAND partition. 

As of now, you must set this up right now by manually copying the file with FBI or GodMode9.
This isn't really a safe method and it makes updating this version of luma a bit more annoying.

So, It'd be nice if you could set it so you can update both the NAND version payload as well as the SD payload whenever you update.

**Comment by gudenau** [comment]
I do not see this mentioned anywhere on the wiki, care to elaborate on how one installs this?

Edit:
I think I figured it out, just copy the payload to the root of CTRNAND. I'll look into making a thing for this later.
