### ISSUE TITLE
no longer working with the hourly builds

### ISSUE THREAD

**Issue by pbanj** [Hamcha/lumaupdate#58]
![IMG](http://i.imgur.com/jbhp4dB.jpg)

**Comment by aaalexxx90** [comment]
Same here
![img_20161106_181028](https://cloud.githubusercontent.com/assets/23296870/20039881/a610672c-a44c-11e6-8d7a-0b6fc29d9d56.jpg)

**Comment by Hubcapp** [comment]
https://astronautlevel2.github.io/Luma3DS/ has 404 for latest build (https://astronautlevel2.github.io/Luma3DS/builds/Luma-f7e57038.zip), that is why this is happening.

it may have to do with this line from @astronautlevel2's readme:

> TODO:
> -    Find another way to store builds before I run out of github space
