### ISSUE TITLE
A few ideas :3

### ISSUE THREAD

**Issue by naendow** [Hamcha/lumaupdate#59]
Hi

So, you can now install Luma3DS on CTRNAND. Could you implement that it updates the file on CTRNAND if one is there? And it would be great if you could move the config file to CTRNAND, too.
Oh yea, there is still one issue. The updater always recognises Luma3DS as a dev-version, even it is not one.

Thx for your attention :)

**Comment by Jimmy-Z** [comment]
I suggest you submit them as multiple issues/feature requests so they can be tracked separately.
