### ISSUE TITLE
[bug] Fix TitleID being shown in FBI instead of Title Name

### ISSUE THREAD

**Issue by favna** [Hamcha/lumaupdate#61]
Currently when looking at FBI->Titles LumaUpdater shows up as `00040000001DEA00` instead of `Luma Updater`. This is an extremely frustrating bug and should be very easy to fix as this is an issue in the way the header is created. If you want an example, a similar bug was fixed long ago in bannertool (and by extension buildtools) so you can look there. If you still using bannertool yourself then please update your version before the next release of LumaUpdater. [Click here for said commit to bannertool](https://github.com/Steveice10/bannertool/commit/24288b4ec6fc03c91643ab6e86847157296e617b) (but just grab the latest version when you do)

**Comment by favna** [comment]
Small update... here is an example image as seen in FBI

![sdadasdasdasdasdasd](https://cloud.githubusercontent.com/assets/4019718/20647096/5a47cd22-b48b-11e6-8ee3-d910a7b373f5.JPG)

**Comment by Hamcha** [comment]
Thank you for the report and solution, I'll see what I can do!

**Comment by favna** [comment]
Oh darn before I forget (I was reminded due to the notification) - It might be that LumaUpdater and PKSM's issues come down to the same so perhaps try looking into it together with Bernado. 2 heads are better than 1 after all.

[I'm saying this in context of this issue I created on the PKSM repo](https://github.com/BernardoGiordano/PKSM/issues/62)

**Comment by favna** [comment]
I'm not sure at which point but this has been fixed in KunoichiZ fork so I may as well close this since that is the most up to date progress anyway.
