### ISSUE TITLE
cannot update Luma3DS

### ISSUE THREAD

**Issue by wiinwinn** [Hamcha/lumaupdate#63]
i cannot update Luma3ds. when i launch the luma Updater v.1.4.2 and update it. 

It always show update failed with the bottom screen shows

"could not get status code
Ret code: -660561850
FATAL
Could not get A9LH payload."

any help ?? really appreciate

**Comment by ghost** [comment]
Oh. That just means that specific commit is not available on the web. It's trying to download something that does not exist, so therefore it returns that error. I had that happen to me back then as well
