### ISSUE TITLE
Configuration not found

### ISSUE THREAD

**Issue by guiscaranse** [Hamcha/lumaupdate#69]
So, I am getting this "Configuration not found, using default values" everytime that i update my luma by the Luma Updater. It causes my luma settings reseting to whatever default configs are.
Any idea how to keep my settings for luma?

**Comment by Committee** [comment]
That error has nothing to do with Luma Settings.

**Comment by Committee** [comment]
Wait double checked, my bad it is related.

**Comment by pbanj** [comment]
OK first off this isn't an issue with the updater. The configuration file for the updater is provided, it isn't needed though. The updaters config has 0 to do with luma and its config. When luma has had a change to its config settings it makes you recreate them. It has nothing to do with the updater and is not even an issue. It is an intended action if the config has changed enough.

**Comment by Hamcha** [comment]
As said by others, "Configuration not found, using default values" is not related to Luma at all and it's not why your Luma resets every time. That message just means you haven't created a custom configuration file for the updater to override any of its default settings (such as disabling logging or changing the payload path or update method). If the updater is working for you, you can just ignore it.
