### ISSUE TITLE
Boot9Strap support

### ISSUE THREAD

**Issue by FateForWindows** [Hamcha/lumaupdate#72]
Since B9S is out, this should be updated to add support for it since support for A9LH will eventually end in the future (pre-A9LH entrypoints had support dropped recently).

**Comment by KunoichiZ** [comment]
I've made a [fork](https://github.com/KunoichiZ/lumaupdate) that supports Boot9strap.

**Comment by ghost** [comment]
The payload type (sighax) in the cfg is marked as wrong

**Comment by KunoichiZ** [comment]
@sercho80 What do you mean? What should it be then?

**Comment by ghost** [comment]
@KunoichiZ my english is really bad, so probably you've misunderstand me. When luma updater 2.0 loads, the bottom screen show me an error and it says the payload type is wrong

**Comment by KunoichiZ** [comment]
@sercho80 Weird. Everyone else that has installed that version has not mentioned that error happening for them. Can you provide a screenshot?

**Comment by ghost** [comment]
@KunoichiZ sorry for the delay, here you have (I tried in two different consoles)
![img_20170521_012342](https://cloud.githubusercontent.com/assets/28808032/26279964/a1b81d20-3dc4-11e7-876f-b2982a5b1999.jpg)
![img_20170521_012120](https://cloud.githubusercontent.com/assets/28808032/26279963/a1b0af18-3dc4-11e7-8815-9e379673defc.jpg)

**Comment by KunoichiZ** [comment]
@sercho80 That's really odd. I have not seen that error nor has anyone else commented on it. I'm not sure what to do.

**Comment by KunoichiZ** [comment]
@sercho80 If you have a file on the root of your SD card called `lumaupdater.cfg`, delete it and try again.

**Comment by ghost** [comment]
@KunoichiZ I have already found the error, you have to put the type in uppercase not in lowercase.
Thanks for all 👍

**Comment by KunoichiZ** [comment]
@sercho80 I'm glad that's all it was. :) You're welcome!
