### ISSUE TITLE
Can't update to Luma 7.1 on Old 3DS XL

### ISSUE THREAD

**Issue by Viridian470** [Hamcha/lumaupdate#73]
It says the following:
Reason for failure: DOWNLOAD FAILED

The bottom screen says the following:
Extracting Payload [ERR]
FATAL: Could not find out /arm9loaderhax.bin in zip fileFATAL

I'm not exactly sure what this means and I'm a little concerned... Can someone help?

**Comment by Toys0125** [comment]
Also having the same problem on the Old 3DS Original with:
FATAL: Could not find arm9loaderhax.binFATAL.
might have a problem with the error code somehow ending up at the end of the payload.

**Comment by Toys0125** [comment]
Found the problem he missing the .bin and named it incorrectly when he uploaded it.
[https://goo.gl/zXdFHj](url)

**Comment by ghost** [comment]
Getting the same problem on 2DS. Won't let me update from 7.0 to 7.1.

EDIT: This is probably because of the transition from .bin to .firm as part of sighax being released

**Comment by Prism019** [comment]
Hey guys. This is due to Boot9Strap being released and Luma3DS dropping support for A9LH. LumaUpdate has not been updated yet to deal with it. Please refer to https://3ds.guide/updating-to-boot9strap and put Luma3DS on there manually.

**Comment by asalazar95** [comment]
Is the current LumaUpdate still directed to arm9, because I've tried updating the updater 3 times and still nothing

**Comment by Prism019** [comment]
Yes. LumaUpdate will not work until it is fixed. All we can do right now is wait.

Also -- IF YOU HAVE NOT SWITCHED TO BOOT9STRAP PLEASE DO SO NOW! ALL FUTURE RELEASES OF LUMA3DS WILL NOT SUPPORT ANYTHING BUT IT! https://3ds.guide/updating-to-boot9strap

**Comment by KunoichiZ** [comment]
I have a [fork](https://github.com/KunoichiZ/lumaupdate) that supports Boot9strap.

**Comment by smokemus** [comment]
Do you need to update luma before following that guide or if I follow it does it do that while doing the prepwork phase?

**Comment by KunoichiZ** [comment]
@smokemus What version of Luma do you currently have?

**Comment by smokemus** [comment]
6.6-B16d887 (dev) is what the updater is saying

**Comment by KunoichiZ** [comment]
@smokemus Update your Luma to v7.0.5, then do the steps to update to boot9strap.

**Comment by Okamiden15** [comment]
@KunoichiZ but how do we do that? it only gives me the option to update to 7.1

**Comment by smokemus** [comment]
So, last noob question I have I hope >.< once I installed the luma payload and powered up the 3ds it brought up the screen to select what nand mode I want to use and I cannot remember what the safe one is. Do I check the Autoboot sysNAND box or just hit start to boot it w/o anything selected? And to answer okamiden, you need to manually DL 7.0.5 from the luma releases on github

**Comment by Okamiden15** [comment]
I did that, do I just transfer it to the root of my sd card?

**Comment by smokemus** [comment]
Yar, thats what everything I've read says you need to do. Just couldn't find out what nand mode It's suppose to be in so you don't accidentally mess things up when doing the reg system update

**Comment by Okamiden15** [comment]
I guess ill just wait till we get a response on the nand mode

**Comment by KunoichiZ** [comment]
@smokemus If you just have a sysNAND, check Autoboot SysNAND. 
@Okamiden15 The same above goes to you too.

**Comment by Okamiden15** [comment]
awesome, thanks

**Comment by smokemus** [comment]
So i hate to be that guy and bring this back up but my comp kinda died a while back and wasnt able to update, so now that im back and have everything going again i see that b9s has had some updates and was wondering if while still on a9lh can i follow the upgrade guide to b9s and install 1.2 or do i have to dl an older version of b9s and then update from there. sorry if this is the wrong place to ask.

**Comment by KunoichiZ** [comment]
@smokemus Just follow the guide to upgrade to b9s and you'll be fine.

**Comment by smokemus** [comment]
tyvm, worked perfectly!

**Comment by Chase13451** [comment]
Ok i updated to boot9strap following https://3ds.guide/a9lh-to-b9s.html and i still get an error saying could not get a9lh payload HELP

**Comment by KunoichiZ** [comment]
@Chase13451 Delete the lumaupdater.cfg file from your SD card root if you have it.

**Comment by Chase13451** [comment]
@KunoichiZ i dont have it

**Comment by KunoichiZ** [comment]
@Chase13451 You aren't using my version of Luma Updater then. It's linked in the a9lh to b9s guide. Download it then try again.

**Comment by Chase13451** [comment]
@KunoichiZ  Thank you!!!! You are amazing,How do you know all this? But i still cant play online how do i check my version??

**Comment by Chase13451** [comment]
nvm i see it im on v8.1. and i can play online thanks

**Comment by KunoichiZ** [comment]
I know all of this because I've helped others like you who have had the same issue. And you're welcome. :)
