### ISSUE TITLE
DOWNLOAD FAILED

### ISSUE THREAD

**Issue by evangeltepes** [Hamcha/lumaupdate#74]
Keep getting issue: DOWNLOAD FAILED when trying to update to 7.1 or even to the hourly build.

Extracting payload [ERR]
FATAL: Could not find out/arm9loaderhax.bin in zip fileFATAL
Could not get A9LH payload...

**Comment by frankyfife** [comment]
Same here with the latest build 7.1

**Comment by KunoichiZ** [comment]
The hourly builds are broken. The reason for the error in @evangeltepes's post is because arm9loaderhax.bin is not longer supported and you can't update to 7.1 or anything above that unless you have boot9strap.
