### ISSUE TITLE
Luma 2.0 hourly update failed

### ISSUE THREAD

**Issue by Anime-knight** [Hamcha/lumaupdate#75]
Reason for failure: DOWNLOAD FAILED
Copying/boot.firm to /boot.firm.bak...
Downloading "insert link"
download progress 158/`58
download complete! size 158
skipping integrity check #1 unknown size
skipping integrity chect #2 no etag found
extracting payload ERR
Fatal could not find out/boot.firm in zip fileFATAL
Could not get sighax payload

**Comment by KunoichiZ** [comment]
The hourlies are currently not working. That's the reason for the error.
