### ISSUE TITLE
Download fails on update to Luma 7.1 on New 3DS XL on 11.3

### ISSUE THREAD

**Issue by The-Hacker894** [Hamcha/lumaupdate#76]
When trying to update from Luma 7.0.4-725a8257 (dev) on Luma Updater v1.4.2 to Luma 7.1 the download fails and prompts to press START to exit.

**Comment by KunoichiZ** [comment]
7.1 only works on boot9strap consoles. If you have a9lh, follow [this](https://3ds.guide/updating-to-boot9strap) to update to boot9strap. 7.0.5 is the last update for non-boot9strap consoles.

**Comment by The-Hacker894** [comment]
Ok, thanks!
