### ISSUE TITLE
luma update to 7.1 Failed 2DS 11.4 {COULD NOT GET A9LH PAYLOAD}

### ISSUE THREAD

**Issue by Zyepto** [Hamcha/lumaupdate#77]

**Comment by KunoichiZ** [comment]
7.1 does not support a9lh. 7.1 requires you to install boot9strap. If you have a9lh installed, follow [this](https://3ds.guide/updating-to-boot9strap).

**Comment by Cantiel** [comment]
i have the same problem. i'm using the nightly build 7.1-c73fec46 (which i needed for the 11.4 update) of luma3ds at the moment, and tried to switch to the latest stable build. i followed the above mentioned guide and installed boot9strap, and deleted a9lh, but it's still giving me an error after asking for the arm9loaderhax.bin

**Comment by KunoichiZ** [comment]
@Cantiel If that text is appearing, then you didn't install v2.0. That text shouldn't be appearing with v2.0 because I replaced that line of code. Can you provide a screenshot? How did you get the nightly build of 7.1?

**Comment by Cantiel** [comment]
i was using v1.4.2, didn't knew there is a fork, or how to find it. but i managed to figure it out and installed v2.0 now. If i remember correctly, i just used the luma-updater and chose the available nightly build at the beginning of may
Could update without problems using the v2.0 updater, thanks for the quick help :)

**Comment by KunoichiZ** [comment]
You're welcome! :)
