### ISSUE TITLE
Update 7.1 failed

### ISSUE THREAD

**Issue by 4chanFag** [Hamcha/lumaupdate#78]
New3ds XL

Error
" Extracting payload [ERR]
   FATAL: Could not find arm9loaderhax.binFatal
   Could not get A9LH payload "

**Comment by KunoichiZ** [comment]
7.1 does not support a9lh. 7.1 requires you to install boot9strap. If you have a9lh installed, follow [this](https://3ds.guide/updating-to-boot9strap).

**Comment by 4chanFag** [comment]
Thank you so much.
