### ISSUE TITLE
DOWNLOAD FAILED

### ISSUE THREAD

**Issue by OfficialBrony** [Hamcha/lumaupdate#79]
You see many other issues related to this one, yet I see the problem has NOT been resolved. Many people say that they're O3DS users, while I am getting the same issue on my N3DSXL. Whether I use my home's WiFi, My mom's Wifi, Turn my phone into a hotspot, it always says download failed...
Like why would it find a new version, if it can't download it???
I should also mention that I am on 11.4
Current version: 7.0.5-e029458b
Latest version (Github) 7.1

**Comment by KunoichiZ** [comment]
7.1 only works on boot9strap consoles. If you have a9lh, follow [this](https://3ds.guide/updating-to-boot9strap) to update to boot9strap. 7.0.5 is the last update for non-boot9strap consoles.
