### ISSUE TITLE
Hourly build hash only displays 7 characters instead of 8

### ISSUE THREAD

**Issue by CaptainSwag101** [Hamcha/lumaupdate#80]
It also might be ignoring leading zeroes in the hash string, because I've seen it cut off the first character when it's a zero, but more recently I've noticed it cutting off the last character. However, the hash for the currently installed version seems to list the hash correctly. Also, I know the following screenshot is from version 2.1 which is a fork of this repo, but I know for certain I've experienced this issue on lumaupdate v1.4.2 several times, so I figured it'd be most appropriate to mention the issue here.

![lumaupdate hash bug](https://cloud.githubusercontent.com/assets/2925767/26466429/9fe72db0-4143-11e7-84f7-607fca1eda6e.jpg)

**Comment by KunoichiZ** [comment]
That will be fixed in my fork.
