### ISSUE TITLE
cannot update hourly version and luma updater 

### ISSUE THREAD

**Issue by tamuaoo** [Hamcha/lumaupdate#83]
hi.

Thanks for luma3ds team....

Now, i have a big problem
I cannot update luma hourly version 90f29af ... and other hourly version (every hourly version)
Reason for failure: Download failed
Download .... Non-200 status code Ret code : 404 FATAL
Please suggest me for update

.............................

and please suggest for update luma3ds updater to 2.1

.............................

my 3ds have luma3ds updater 2.0

Thank you very much

**Comment by l3dz3pp** [comment]
I have the same problem and don't know what to do.
Thanks

**Comment by KunoichiZ** [comment]
Hourlies are broken, to my knowledge. Please stick to the latest stable.

**Comment by tamuaoo** [comment]
I have new problem

I update hourly version
and i got the massage

in case something goes wrong you can restore the old payload from /boot.firm.bak

So, I never update luma hourly version 
it happen again and again

and i cannot boot my 3ds
i use my boot.firm.bak for solve problem now
but i cannot know true problem

please suggest me
thank you

**Comment by KunoichiZ** [comment]
@tamuaoo I already told you. The hourlies are broken for now. Please stick to the latest stable version for the time being. DO NOT UPDATE TO THE HOURLIES. This is the last time I'm telling you this. :/

**Comment by Baxi2** [comment]
Hey, KunoichiZ is the new stable version avaible  `?

**Comment by tamuaoo** [comment]
Thanks @KunoichiZ for your answer
I will follow your suggestion.

but, Why Hourly version came for update many version 
if broken Hourly version, Team luma should be to announce everyone
T T

**Comment by KunoichiZ** [comment]
@Baxi2 The stable version of Luma's been available for awhile now.
@tamuaoo People are generally not supposed to use the hourly builds as they are often unstable and won't be supported by the Luma devs, and as such, they don't feel the need to announce: "hey hourly builds are broken/unstable. do not use."

**Comment by ShadowNA** [comment]
Tamuaoo
Can you tell me how you geht the hourly Version to download?
I know i should use the stabile versions only, but i want to know it, because it is my risk
Would be nice of you tell me how

**Comment by KunoichiZ** [comment]
@ShadowNA You would use Luma Updater to download it, but as of right now, the hourly builds lead to your system not properly booting until you restore your previous boot.firm. It's best to not deal with it at all.

**Comment by tamuaoo** [comment]
Thanks @KunoichiZ

**Comment by tamuaoo** [comment]
Now, I can update Hourly version 
after update i got a massage tell me something wrong
but i can boot my 3ds and play game
I don't restore previous boot.firm file

**Comment by KunoichiZ** [comment]
@tamuaoo I don't know what to tell you.

**Comment by Nivan0712** [comment]
I have a problem.. i can't update my luma Updater..
Its actually on: v1.4.1
"Update failed
Something went wrong while to update, see screen below for details.
Reason for failure: Downloads Failed"

Current isntalled version: 7.0.5-f5aa6393 (dev)
Latest version (Github): 7.1
Latest hourly build: 4c87800

"Extracting payload (ERR)
FATAL: Could not find arm9loaderhax.binFATAL
Could not get A9LH payload..."

Install normal and hourly dont work :/

**Comment by KunoichiZ** [comment]
@Nivan0712 Luma3DS 7.1+ and any new hourlies require boot9strap. Update to it [here](https://3ds.guide/a9lh-to-b9s). Luma3DS has dropped support for a9lh.

**Comment by Baxi2** [comment]
are the hourly version available soon ?

**Comment by ShadowNA** [comment]
They are available, nur You Neef to have boot9strap Version 1.2 and luma3ds 8.0 Rosalina update
