### ISSUE TITLE
Unable to uninstall Luma updater 

### ISSUE THREAD

**Issue by Antari18** [Hamcha/lumaupdate#84]
So I've upgraded to b9s from a9lh and installed luma 8.0 and Luma installer 2.1.2. The problem is, I haven't uninstalled Luma installer 1.4.2 before and now I have 2 Luma installers on home menu. 

I can't uninstall 1.4.2 because it does not appear on tickets. Only 2.1.2 version appear on tickets. How do I get rid of 1.4.2?

**Comment by DakuTree** [comment]
Just had the same issue.  
Seems like the old updater was missing the title name, but it should still show as: `00040000001DEA00` with the product code `CTR-L-UPDR`. Deleting that will uninstall the old updater.
