### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by albatros2808** [Hamcha/lumaupdate#86]
hi, when I'm trying to update my luma (it is on version 6.5 and I'm trying to go to version 8.0) whenever I'm trying to install the update it says update fails and the error that shows on the touch screen is could not get a9lh payload... is there any way of fixing this issue?
and another question that I don't know if its relevant to this place I have updated the Nintendo firmware to 11.4 and since the update my r4 gold card isn't responding its just go to black screen do you guys know how to fix this? thanks!

**Comment by KunoichiZ** [comment]
You need to install boot9strap to take advantage of Luma v8.0+. Go [here](https://3ds.guide/a9lh-to-b9s) to update to b9s. I don't know how to fix the r4 gold card issue, nor do I care because it doesn't relate to Luma Updater at all.
