### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by MidgeThePidge** [Hamcha/lumaupdate#87]
Tried updating from 8.0 to 8.1 and got the error ''UPDATE FAILED" in red letters.

**Comment by KunoichiZ** [comment]
1) Wrong Github page. 
2) I'm trying to work on that.

**Comment by MidgeThePidge** [comment]
Oh, when I got the error it told me to go to this page. I did get it updated by replacing the boot.firm manually though so it's all good!
