### ISSUE TITLE
homebrew applications not working after lumaupdate 

### ISSUE THREAD

**Issue by Vaspro123** [Hamcha/lumaupdate#89]
When I go to the homebrew on my new 3ds and try to go on an application I get this error 
![dsc_0035](https://user-images.githubusercontent.com/30029196/27997777-63b3420c-64f7-11e7-9bf5-91df8d2588f9.JPG) I have only recieved this after the update to luma 8.0 any feedback would be very helpful

**Comment by sks316** [comment]
This wouldn't be the repo for that. You're looking for [AuroraWright/Luma3DS](https://github.com/AuroraWright/Luma3DS/issues).

**Comment by Vaspro123** [comment]
Thank you
