### ISSUE TITLE
Can't install Luma3DS 8.1.1

### ISSUE THREAD

**Issue by Clement95** [Hamcha/lumaupdate#93]
When I starts the software, it says the current version installed od Luma3DS is 8.1 and a new version is available (8.1.1) When I try to install it "Download Failed".

**Comment by bakker1337** [comment]
I have the same issue. I currently have Luma 6.6 and can't update to 8.1.1 either.

**Comment by KunoichiZ** [comment]
@Clement95 Try downloading it again. Also, since you are using my fork, you should have posted your issue [here](https://github.com/KunoichiZ/lumaupdate/issues) instead of this issue page.
@bakker1337 Download Luma3DS v7.0.5 and copy the arm9loaderhax.bin from that release to your SD card root. Then, follow [this](https://3ds.guide/a9lh-to-b9s). Luma3DS no longer supports a9lh.

**Comment by Clement95** [comment]
Yes, sorry, and it still doesn't work..

**Comment by KunoichiZ** [comment]
@Clement95 It works for me. Try redownloading Luma Updater.

**Comment by bakker1337** [comment]
I got boot9strap. It works now.

**Comment by Clement95** [comment]
I tried to uninstall and desinstall Luma 3DS Updater and it also doesn't work :/

**Comment by KunoichiZ** [comment]
@Clement95 I don't know what to tell you because it works for me. :/ Are you sure you have boot9strap v1.2 (meaning you are able to run Luma v8.0)?

**Comment by Clement95** [comment]
Actually, I had really a 8.1.1 version but Luma3DS Updater shows me a
new version 8.1.1 is available

**Comment by KunoichiZ** [comment]
I don't know how to help you then. Sorry.

**Comment by Clement95** [comment]
Np, thanks ;)

**Comment by StarofSpace** [comment]
Hi KunoichiZ, I just signed up to say this worked for me! Thanks!
Actually, the only reason I was looking into this is because some of my virtual console games weren't launching, but they're working now thankfully.

**Comment by KunoichiZ** [comment]
@StarofSpace I'm glad that I was able to help! :)

**Comment by ghost** [comment]
KunoichiZ porque existen dos Luma Updater, uno de KunoichiZ y Hamcha y otro de Hamcha solo?

**Comment by KunoichiZ** [comment]
@JorgeProGamer I don't speak any other languages other than English. My version of Luma Updater is for boot9strap users.

**Comment by ghost** [comment]
Gracias por responder.

**Comment by Clement95** [comment]
Uno es por arm9loaderhax (armloaderhax.bin) y uno por boot9strap (boot.firm)
