### ISSUE TITLE
how do we get luma 2.0?

### ISSUE THREAD

**Issue by Haithius** [Hamcha/lumaupdate#94]
So for a while know ive had my 2ds on ver. 11.3.0-36U and ive been playing a game on it, butr now for me to play online i have to update, i dont really wanna do this becuase i got the game off of freeshop. I would like to know how to get luma 2.0 because everywere i look it says to use luma but then i get on here and it says i need 2.0 but i dont understand how to get it when it says that the lastest version is what 1.4.2?... It would be great if someone could help, thanks. ( :

**Comment by KunoichiZ** [comment]
It's recommended you [update to boot9strap](https://3ds.guide/a9lh-to-b9s). If you follow the guide, you'll be prompted to download and install my fork of Luma Updater, which is v2.0+.
