### ISSUE TITLE
Luma wont update.

### ISSUE THREAD

**Issue by GooeyMoney** [Hamcha/lumaupdate#95]
I havent used my 3ds in a few months and my luma is still on 6.6, when i use the luma updater 2.2 or 2.1.2 (tried both) and choose to install stable version, it says it installs it, but when it reboots and i open luma updater it says im still on 6.6

**Comment by KunoichiZ** [comment]
That's because you need boot9strap. Using my fork of Luma Updater does nothing for you right now as you still have a9lh. Follow [this guide](https://3ds.guide/a9lh-to-b9s) and then you'll be able to use my fork of Luma Updater. Next time you have an issue, please post the issue in the correct repo.
