### ISSUE TITLE
Unable to update Luma to 8.1

### ISSUE THREAD

**Issue by clementine15** [Hamcha/lumaupdate#96]
I am having a lot of trouble with updating Luma. I am following this [guide](https://3ds.guide/a9lh-to-b9s), and I am stuck at step 2. For some reason, even though I hold down start, my 3DS loads up normally. It does not launch to SafeB9SInstaller.

When I try to update Luma using my 3DS, I get a "Download Failed" error, and a description saying "Ret code: 404, FATAL, Could not get A9LH payload." How do I fix this? I am using a N3DS

**Comment by KunoichiZ** [comment]
Make sure you have every file downloaded and in the right place. You haven't followed the instructions fully. Luma no longer supports a9lh so you can no longer download an updated arm9loaderhax.bin file.
