### ISSUE TITLE
Unable to Update Luma3ds

### ISSUE THREAD

**Issue by slinares03** [Hamcha/lumaupdate#97]
I have a o3ds and it is currently in Luma 6.6-b1bd887 and I tried to install "The Stable Version" which is 9.0 but every time i choose that option. It just downloads it and it doesnt install it just shows up as "current backup version", perhaps im just a noob and have to install it manually but idk. So please help me, thank you.

**Comment by KunoichiZ** [comment]
[https://3ds.guide/a9lh-to-b9s](https://3ds.guide/a9lh-to-b9s)

Follow that. Luma no longer supports a9lh and you need to switch to boot9strap to update your Luma version.
