### ISSUE TITLE
ARM11 support for emulators

### ISSUE THREAD

**Issue by jem999** [Hamcha/lumaupdate#98]
Having problems with ARM11 causing RetroArch to crash I need better support with LUMA and ARM11

**Comment by KunoichiZ** [comment]
I'm not supporting emulators. Sorry. Also, you don't need anything. You want.

Also, I believe you are in the wrong repo. You might be looking for the [Luma3DS repo](https://github.com/AuroraWright/Luma3DS). The updater and Luma3DS are not the same thing.
