### ISSUE TITLE
Luma update 2.2 dont work

### ISSUE THREAD

**Issue by Daulidas** [Hamcha/lumaupdate#99]
Hi, i have this lil problem 
![img_2253](https://user-images.githubusercontent.com/36800414/36634465-c77588ea-1983-11e8-89a2-2be74e1da936.jpg)
My internet connection is ok btw...

**Comment by ghost** [comment]
Please visit this site:https://www.reddit.com/r/3dshacks/comments/7uem9t/psa_many_homebrew_applications_such_as_luma3ds/

**Comment by KunoichiZ** [comment]
Please take this to the [correct repo](https://github.com/KunoichiZ/lumaupdate) next time. This repo, as the [README](https://github.com/Hamcha/lumaupdate/blob/master/README.md) states, is no longer being maintained. Use my fork for all future bug issues. Yes, I know this problem exists. Yes, I'm working on a fix.
